apiVersion: v1
kind: Service
metadata:
  name: {{ template "superset.fullname" . }}-service
  labels:
    app: {{ template "superset.name" . }}
    chart: {{ template "superset.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8088
      protocol: TCP
      name: http
  selector:
    app: {{ template "superset.name" . }}
    release: {{ .Release.Name }}
