kafkaExporter:
  zookeeper:
    servers: ["{{ processing_cluster_zookeeper }}"]
  kafka:
    servers: ["{{ processing_cluster_kafka }}"]
  additionalFlags:
    - --use.consumelag.zookeeper

prometheus:
  serviceMonitor:
    enabled: true
    namespace: monitoring
    interval: "120s"
    scrapeTimeout: "90s"
    additionalLabels:
      app: prometheus-operator
      release: prometheus-operator
